// Package cve implements a Renovate-style CVE watcher that correlates
// Beacon findings with dependency databases to generate targeted upgrade PRs.
//
// Flow:
//  1. Receive Beacon findings (especially supply_chain.* and version.* checks)
//  2. For each finding with a CVE reference, look up the fix version
//  3. Search the traced repo for the vulnerable dependency
//  4. Generate a PR that upgrades to the fixed version
package cve

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// Advisory represents a CVE advisory with fix information.
type Advisory struct {
	// CVEID is the CVE identifier (e.g., "CVE-2024-1234").
	CVEID string `json:"cve_id"`

	// Severity from the advisory: critical, high, medium, low.
	Severity string `json:"severity"`

	// Package is the affected package name (e.g., "github.com/golang/go").
	Package string `json:"package"`

	// Ecosystem is the package ecosystem: "go", "npm", "pip", "maven", "cargo".
	Ecosystem string `json:"ecosystem"`

	// VulnerableVersions is a version constraint for affected versions.
	VulnerableVersions string `json:"vulnerable_versions"`

	// FixedVersion is the first version that contains the fix.
	FixedVersion string `json:"fixed_version"`

	// Summary is a human-readable description.
	Summary string `json:"summary"`

	// References are URLs with more information.
	References []string `json:"references"`
}

// UpgradePR represents a suggested dependency upgrade PR.
type UpgradePR struct {
	// Repo is the target repository (owner/name).
	Repo string `json:"repo"`

	// FilePath is the dependency file to modify (go.mod, package.json, etc.).
	FilePath string `json:"file_path"`

	// Package is the package to upgrade.
	Package string `json:"package"`

	// CurrentVersion is the currently used version.
	CurrentVersion string `json:"current_version"`

	// TargetVersion is the version to upgrade to (the fix version).
	TargetVersion string `json:"target_version"`

	// Advisory is the CVE advisory that triggered this upgrade.
	Advisory Advisory `json:"advisory"`

	// Title is the suggested PR title.
	Title string `json:"title"`

	// Body is the suggested PR body.
	Body string `json:"body"`

	// Branch is the suggested branch name.
	Branch string `json:"branch"`
}

// Watcher monitors Beacon findings for CVE-related issues and generates
// upgrade PRs.
type Watcher struct {
	ghToken string
	baseURL string
	client  *http.Client
}

// New creates a CVE Watcher.
func New(githubToken string) *Watcher {
	return &Watcher{
		ghToken: githubToken,
		baseURL: "https://api.github.com",
		client:  &http.Client{Timeout: 30 * time.Second},
	}
}

// SetBaseURL overrides the API URL (for testing).
func (w *Watcher) SetBaseURL(url string) {
	w.baseURL = strings.TrimSuffix(url, "/")
}

// Finding is the subset of Beacon findings that the CVE watcher needs.
type Finding struct {
	CheckID  string         `json:"check_id"`
	Asset    string         `json:"asset"`
	Title    string         `json:"title"`
	Evidence map[string]any `json:"evidence"`
}

// GenerateUpgrades takes Beacon findings with CVE references and produces
// upgrade PR suggestions for the repos that deploy the affected assets.
func (w *Watcher) GenerateUpgrades(ctx context.Context, findings []Finding, repoLinks map[string]string) ([]UpgradePR, error) {
	var upgrades []UpgradePR

	for _, f := range findings {
		if ctx.Err() != nil {
			break
		}

		// Extract CVE ID from evidence.
		cveID, ok := extractCVE(f)
		if !ok {
			continue
		}

		// Look up the advisory.
		advisory, err := w.lookupAdvisory(ctx, cveID)
		if err != nil {
			continue
		}

		// Find the repo that deploys this asset.
		repo, ok := repoLinks[f.Asset]
		if !ok {
			continue
		}

		// Search the repo for the vulnerable dependency.
		depFile, currentVersion, err := w.findDependency(ctx, repo, advisory)
		if err != nil || depFile == "" {
			continue
		}

		upgrade := UpgradePR{
			Repo:           repo,
			FilePath:       depFile,
			Package:        advisory.Package,
			CurrentVersion: currentVersion,
			TargetVersion:  advisory.FixedVersion,
			Advisory:       *advisory,
			Branch:         fmt.Sprintf("bosun/fix-%s", strings.ReplaceAll(cveID, ".", "-")),
			Title:          fmt.Sprintf("fix(%s): upgrade %s to %s (%s)", ecosystemShort(advisory.Ecosystem), advisory.Package, advisory.FixedVersion, cveID),
			Body: fmt.Sprintf(`## Security Fix

Upgrades **%s** from %s to %s to fix [%s](%s).

### Advisory

%s

**Severity:** %s

### What changed

This is an automated dependency upgrade generated by Bosun based on a
live Beacon scan finding on asset %s.

---
Generated by Bosun
`, advisory.Package, currentVersion, advisory.FixedVersion, cveID,
				fmt.Sprintf("https://nvd.nist.gov/vuln/detail/%s", cveID),
				advisory.Summary, advisory.Severity, f.Asset),
		}

		upgrades = append(upgrades, upgrade)
	}

	return upgrades, nil
}

func extractCVE(f Finding) (string, bool) {
	// Check evidence for CVE references.
	if f.Evidence != nil {
		for _, key := range []string{"cve", "cve_id", "vulnerability", "advisory"} {
			if v, ok := f.Evidence[key]; ok {
				if s, ok := v.(string); ok && strings.HasPrefix(s, "CVE-") {
					return s, true
				}
			}
		}
	}

	// Check if the title contains a CVE.
	if idx := strings.Index(f.Title, "CVE-"); idx >= 0 {
		end := idx + 4
		for end < len(f.Title) && (f.Title[end] >= '0' && f.Title[end] <= '9' || f.Title[end] == '-') {
			end++
		}
		return f.Title[idx:end], true
	}

	return "", false
}

// lookupAdvisory queries the GitHub Advisory Database for CVE details.
func (w *Watcher) lookupAdvisory(ctx context.Context, cveID string) (*Advisory, error) {
	// Use GitHub's advisory database API.
	url := fmt.Sprintf("%s/advisories?cve_id=%s", w.baseURL, cveID)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+w.ghToken)
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := w.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("advisory lookup %d: %s", resp.StatusCode, body)
	}

	var advisories []struct {
		GHSAID      string `json:"ghsa_id"`
		CVEID       string `json:"cve_id"`
		Summary     string `json:"summary"`
		Severity    string `json:"severity"`
		References  []string `json:"references"`
		Vulnerabilities []struct {
			Package struct {
				Ecosystem string `json:"ecosystem"`
				Name      string `json:"name"`
			} `json:"package"`
			VulnerableVersionRange string `json:"vulnerable_version_range"`
			FirstPatchedVersion    struct {
				Identifier string `json:"identifier"`
			} `json:"first_patched_version"`
		} `json:"vulnerabilities"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&advisories); err != nil {
		return nil, err
	}

	if len(advisories) == 0 {
		return nil, fmt.Errorf("no advisory found for %s", cveID)
	}

	a := advisories[0]
	advisory := &Advisory{
		CVEID:      a.CVEID,
		Severity:   a.Severity,
		Summary:    a.Summary,
		References: a.References,
	}

	if len(a.Vulnerabilities) > 0 {
		v := a.Vulnerabilities[0]
		advisory.Package = v.Package.Name
		advisory.Ecosystem = strings.ToLower(v.Package.Ecosystem)
		advisory.VulnerableVersions = v.VulnerableVersionRange
		advisory.FixedVersion = v.FirstPatchedVersion.Identifier
	}

	return advisory, nil
}

// findDependency searches a repo for the vulnerable dependency file.
func (w *Watcher) findDependency(ctx context.Context, repo string, advisory *Advisory) (string, string, error) {
	// Determine which file to look for based on ecosystem.
	depFiles := ecosystemFiles(advisory.Ecosystem)
	if len(depFiles) == 0 {
		return "", "", fmt.Errorf("unsupported ecosystem: %s", advisory.Ecosystem)
	}

	for _, depFile := range depFiles {
		// Try to fetch the file content.
		content, err := w.getFileContent(ctx, repo, depFile)
		if err != nil {
			continue
		}

		// Search for the package in the file.
		if strings.Contains(content, advisory.Package) {
			// Extract current version (simplified — real implementation
			// would parse the dependency file properly).
			version := extractVersion(content, advisory.Package, advisory.Ecosystem)
			return depFile, version, nil
		}
	}

	return "", "", fmt.Errorf("dependency %s not found in %s", advisory.Package, repo)
}

func (w *Watcher) getFileContent(ctx context.Context, repo, path string) (string, error) {
	url := fmt.Sprintf("%s/repos/%s/contents/%s", w.baseURL, repo, path)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("Authorization", "Bearer "+w.ghToken)
	req.Header.Set("Accept", "application/vnd.github.raw+json")

	resp, err := w.client.Do(req)
	if err != nil {
		return "", err
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("get file %d", resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	return string(body), err
}

func ecosystemFiles(ecosystem string) []string {
	switch ecosystem {
	case "go":
		return []string{"go.mod", "go.sum"}
	case "npm":
		return []string{"package.json", "package-lock.json"}
	case "pip":
		return []string{"requirements.txt", "setup.py", "pyproject.toml"}
	case "maven":
		return []string{"pom.xml"}
	case "cargo":
		return []string{"Cargo.toml", "Cargo.lock"}
	case "nuget":
		return []string{"*.csproj", "packages.config"}
	default:
		return nil
	}
}

func ecosystemShort(ecosystem string) string {
	switch ecosystem {
	case "go":
		return "deps"
	case "npm":
		return "deps"
	case "pip":
		return "deps"
	default:
		return "deps"
	}
}

func extractVersion(content, pkg, ecosystem string) string {
	// Simplified version extraction. A production implementation would
	// use proper parsers for each ecosystem's lockfile format.
	lines := strings.Split(content, "\n")
	for _, line := range lines {
		if strings.Contains(line, pkg) {
			// For go.mod: "require github.com/foo/bar v1.2.3"
			parts := strings.Fields(line)
			for _, p := range parts {
				if strings.HasPrefix(p, "v") && strings.Contains(p, ".") {
					return p
				}
			}
		}
	}
	return "unknown"
}
