// Package backstage generates Backstage software template YAML files from
// the Bosun catalog. These templates can be imported into a Backstage
// instance so developers can scaffold security-hardened infrastructure
// directly from the Backstage UI.
//
// Output format follows the Backstage Software Templates spec:
// https://backstage.io/docs/features/software-templates/
package backstage

import (
	"fmt"
	"strings"

	"github.com/stormbane-security/bosun/pkg/catalog"
)

// GenerateAll produces Backstage template YAML for every catalog entry.
// Returns a map of file paths to YAML content.
func GenerateAll() map[string]string {
	files := make(map[string]string)
	for _, entry := range catalog.All() {
		path := fmt.Sprintf("backstage/templates/%s/template.yaml", entry.ID)
		files[path] = GenerateTemplate(entry)
	}

	// Also generate a catalog-info.yaml that registers all templates.
	files["backstage/catalog-info.yaml"] = generateCatalogInfo(catalog.All())

	return files
}

// GenerateTemplate produces a single Backstage template YAML from a catalog entry.
func GenerateTemplate(entry catalog.Entry) string {
	var b strings.Builder

	fmt.Fprintf(&b, `apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: %s
  title: "%s"
  description: "%s"
  tags:
`, entry.ID, entry.Name, escapeYAML(entry.Description))

	for _, tag := range entry.Tags {
		fmt.Fprintf(&b, "    - %s\n", tag)
	}

	fmt.Fprintf(&b, `  annotations:
    bosun/provider: "%s"
    bosun/category: "%s"
spec:
  type: infrastructure
  owner: platform-team
  lifecycle: production
`, entry.Provider, entry.Category)

	// Security notes as extended description.
	if len(entry.SecurityNotes) > 0 {
		b.WriteString("  # Security hardening applied by Bosun:\n")
		for _, note := range entry.SecurityNotes {
			fmt.Fprintf(&b, "  # - %s\n", note)
		}
	}

	// Parameters section.
	b.WriteString("  parameters:\n")
	b.WriteString("    - title: Configuration\n")
	b.WriteString("      required:\n")
	for _, p := range entry.Params {
		if p.Required {
			fmt.Fprintf(&b, "        - %s\n", p.Name)
		}
	}
	b.WriteString("      properties:\n")
	for _, p := range entry.Params {
		fmt.Fprintf(&b, "        %s:\n", p.Name)
		fmt.Fprintf(&b, "          title: \"%s\"\n", p.Label)
		if p.Description != "" {
			fmt.Fprintf(&b, "          description: \"%s\"\n", escapeYAML(p.Description))
		}
		switch p.Type {
		case "number":
			b.WriteString("          type: number\n")
		case "boolean":
			b.WriteString("          type: boolean\n")
		case "enum":
			b.WriteString("          type: string\n")
			b.WriteString("          enum:\n")
			for _, v := range p.Enum {
				fmt.Fprintf(&b, "            - %s\n", v)
			}
		default:
			b.WriteString("          type: string\n")
		}
		if p.Default != "" {
			fmt.Fprintf(&b, "          default: \"%s\"\n", p.Default)
		}
	}

	// Steps section — runs Bosun to generate the Terraform.
	b.WriteString(`  steps:
    - id: bosun-generate
      name: Generate security-hardened infrastructure
      action: bosun:scaffold
      input:
        catalogId: ` + entry.ID + "\n")
	b.WriteString("        params:\n")
	for _, p := range entry.Params {
		fmt.Fprintf(&b, "          %s: ${{ parameters.%s }}\n", p.Name, p.Name)
	}

	b.WriteString(`    - id: publish
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "feat: scaffold ` + entry.Name + `"
        branchName: bosun/scaffold-` + entry.ID + `
        description: |
          ## Infrastructure Scaffold

          Generated by Bosun via Backstage.

          ### Security Hardening
`)
	for _, note := range entry.SecurityNotes {
		fmt.Fprintf(&b, "          - %s\n", note)
	}

	b.WriteString(`
  output:
    links:
      - title: Pull Request
        url: ${{ steps['publish'].output.remoteUrl }}
`)

	return b.String()
}

func generateCatalogInfo(entries []catalog.Entry) string {
	var b strings.Builder

	b.WriteString(`# Bosun security-hardened infrastructure templates for Backstage.
# Import this file into your Backstage app-config.yaml:
#
#   catalog:
#     locations:
#       - type: url
#         target: https://github.com/your-org/bosun-templates/blob/main/backstage/catalog-info.yaml
#
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: bosun-templates
  description: Security-hardened infrastructure templates by Bosun
spec:
  targets:
`)
	for _, e := range entries {
		fmt.Fprintf(&b, "    - ./templates/%s/template.yaml\n", e.ID)
	}

	return b.String()
}

func escapeYAML(s string) string {
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
